FeiuCRM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .view import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crm/', include('crm.urls', namespace='crm')),
    path('djadmin/', include('djadmin.urls', namespace='djadmin')),
    path('login/', user_login, name='user_login'),  # 用户登录
    path('logout/', user_logout, name='user_logout'),  # 退出登录
]

# 上传的文件能直接通过url打开
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/urls.py
from django.urls import path
from .views import index


app_name = 'crm'

urlpatterns = [

    path('', index, name='index'),
]

djadmin/urls.py
from django.urls import path
from djadmin.views import index, user_login, user_logout, table_detail, table_change, table_add,table_delete

app_name = 'djadmin'

urlpatterns = [
    path('login/', user_login, name='user_login'),  # djAdmin登录
    path('logout/', user_logout, name='user_logout'),  # djAdmin登出
    path('<str:app_name>/<str:model_name>/', table_detail, name='table_detail'),  # 数据表详情
    path('<str:app_name>/<str:model_name>/add/', table_add, name='table_add'),  # 数据增加
    path('<str:app_name>/<str:model_name>/<str:obj_id>/change', table_change, name='table_change'),  # 数据表修改
    path('<str:app_name>/<str:model_name>/<int:obj_id>/delete/', table_delete, name='table_delete'),  # 数据表删除
    path('', index, name='index'),  # djAdmin主页
]

djadmin/models.py
from django.db import models

# Create your models here.

djadmin/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from djadmin import app_setup

app_setup.djadmin_auto_discover()
from djadmin.sites import site

print('site:', site.enable_admins)

def user_login(request):
    login_msg = ''
    if request.method == 'POST':
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)
        next_url = request.GET.get('next')

        # 验证帐密
        user = authenticate(username=username, password=password)
        if user:
            # 登录并生成session
            login(request, user)
            if next_url:
                return redirect(next_url)
            return redirect(reverse('djadmin:index'))
        login_msg = '用户名或密码错误！'
    return render(request, 'djadmin/login.html', locals())


def user_logout(request):
    logout(request)
    return redirect(reverse('djadmin:user_login'))

@login_required
def index(request):
    print(site)
    return render(request, 'djadmin/index.html',
                  {
                      'site': site
                  }
                  )


def get_filter_result(request, queryset):
    """获取过滤的字段，并返回过滤后的查询集和过滤的字典"""
    filter_conditions = {}
    # 获取过滤的字段
    for k, v in request.GET.items():
        # 分页将不计入筛选值
        if k == 'page' or k.startswith('_'):
            continue
        if v:  # 所选的值不会空是保存到字典中
            filter_conditions[k] = v
    return queryset.filter(**filter_conditions), filter_conditions


from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator


# @login_required
# def table_detail(request, app_name, model_name):
#     """取出指定model里的数据返回到前端"""
#     # 拿到admin_class后，通过它获取model
#     admin_class = site.enable_admins[app_name][model_name]
#     # print(admin_class)  # 执行djadmin.py定义的注册模型类
#     queryset = admin_class.model.objects.all()
#     # print(queryset)
#
#     # 进行过滤
#     queryset, filter_conditions = get_filter_result(request, queryset)
#     # 将过滤字典保存到全局注册类中
#     admin_class.filter_conditions = filter_conditions
#
#     # 排序，返回排序的结果和排序的字段字典
#     queryset, current_order_field = get_order_result(request, queryset, admin_class)
#     # 如果有排序，保存排序的值，用于模板中在分页模块显示
#     if current_order_field.values():
#         current_order_value = list(current_order_field.values())[0]
#     else:
#         current_order_value = ''
#
#     # 查询集结果分页
#     paginator = Paginator(queryset, 10)  # Show 10 contacts per page
#     page = request.GET.get('page')
#     try:
#         queryset = paginator.get_page(page)
#     except PageNotAnInteger:
#         queryset = paginator.get_page(1)
#     except EmptyPage:
#         queryset = paginator.get_page(paginator.num_pages)
#
#     return render(request, 'djadmin/table_detail.html', locals())


def get_order_result(request, queryset, admin_class):
    """获取request中的排序字段，然后返回排序后的结果"""
    current_order_field = dict()
    # 通过获取前端传过来的排序的索引字符串
    order_value = request.GET.get('_order')  # _order的值为list_display列表的索引：-0, 0, 1, -3等
    if order_value:
        # 通过索引找到要排序的字段，因为索引可能是正数或负数，所以要用绝对值
        order_field = admin_class.list_display[abs(int(order_value))]
        # 记录当前的排序字段，以list_display列表的值为键，request的值为值保存到字典中
        current_order_field[order_field] = order_value
        # 判断是正序或者是倒序，如果是倒序，需要添加负号
        if order_value.startswith('-'):
            order_field = '-' + order_field
        return queryset.order_by(order_field), current_order_field
    else:
        return queryset, current_order_field


def get_search_result(request, queryset, admin_class):
    """搜索"""
    keyword = request.GET.get('_kw', '')
    if keyword:
        from django.db.models import Q
        q = Q()
        q.connector = 'OR'

        for search_field in admin_class.search_fields:
            q.children.append(("{}__contains".format(search_field), keyword))
        print(q)  # (OR: contact__contains, consultant__name__contains)
        queryset = queryset.filter(q)
    return queryset, keyword

@login_required
def table_detail(request, app_name, model_name):
    """取出指定model里的数据返回到前端"""
    # 拿到admin_class后，通过它获取model
    admin_class = site.enable_admins[app_name][model_name]
    # print(admin_class)  # 执行djadmin.py定义的注册模型类
    # POST提交，djadmin actions
    if request.method == 'POST':
        if request.POST.get('action') and request.POST.get('selected_ids'):
            # 获取action，这个action是从djadmin中actions列表中定义的
            selected_action = request.POST.get('action')
            # 获取选中的id
            import json
            print(request.POST.get('selected_ids'))  # json数据["7","6","3"]
            selected_ids = json.loads(request.POST.get('selected_ids'))
            print(selected_ids)  # 列表类型：['7', '6', '3']
            # 获取所有选中id的对象
            selected_objs = admin_class.model.objects.filter(id__in=selected_ids)
            # 获取djadmin中定义的actions函数
            admin_action_func = getattr(admin_class, selected_action)

            # 默认删除功能
            if selected_action == 'delete_selected_objs':
                print('执行{}删除功能'.format(selected_action))
                # 默认情况下显示table_delete.objs.html的内容
                return admin_action_func(request, selected_objs)  # 返回admin_action_func执行方法不用再跳回来

            # 将查询集执行action的功能
            admin_action_func(request, selected_objs)
            print('执行{}的功能！'.format(selected_action))
            # 防止刷新网页提交，使用跳转
            return redirect(reverse('djadmin:table_detail', args=(app_name, model_name)))
    queryset = admin_class.model.objects.all()
    # print(queryset)

    # 进行过滤
    queryset, filter_conditions = get_filter_result(request, queryset)
    # 将过滤字典保存到全局注册类中
    admin_class.filter_conditions = filter_conditions

    # 搜索
    queryset, keyword = get_search_result(request, queryset, admin_class)
    admin_class.search_keyword = keyword  # 将搜索字符串保存到全局类中

    # 排序，返回排序的结果和排序的字段字典
    queryset, current_order_field = get_order_result(request, queryset, admin_class)
    # print(current_order_field)  # {'consult_content': '4'}
    # 如果有排序，保存排序的值，用于模板中在分页模块显示
    if current_order_field.values():
        current_order_value = list(current_order_field.values())[0]
    else:
        current_order_value = ''

    # 查询集结果分页
    paginator = Paginator(queryset, admin_class.list_per_page)  # Show 10 contacts per page
    page = request.GET.get('page')
    try:
        queryset = paginator.get_page(page)
    except PageNotAnInteger:
        queryset = paginator.get_page(1)
    except EmptyPage:
        queryset = paginator.get_page(paginator.num_pages)

    return render(request, 'djadmin/table_detail.html', locals())

# 数据修改
@login_required
def table_change(request, app_name, model_name, obj_id):
    from .form_handle import create_dynamic_model_form
    admin_class = site.enable_admins[app_name][model_name]
    model_form = create_dynamic_model_form(admin_class=admin_class)
    # 实例化
    obj = admin_class.model.objects.get(id=obj_id)  # 获取修改的实例，并将原值初始化到表单中
    form_obj = model_form(instance=obj)

    if request.method == 'POST':
        form_obj = model_form(instance=obj, data=request.POST)
        # print(form_obj.errors)
        if form_obj.is_valid():
            form_obj.save()
            # 修改保存成功后跳转
            return redirect(reverse('djadmin:table_detail', kwargs={'app_name': app_name, 'model_name': model_name}))
    return render(request, 'djadmin/table_edit.html', locals())

# 数据添加
@login_required
def table_add(request, app_name, model_name):
    from .form_handle import create_dynamic_model_form
    admin_class = site.enable_admins[app_name][model_name]
    model_form = create_dynamic_model_form(admin_class=admin_class, form_add=True)  # 增加数据设置form_add为True

    form_obj = model_form()
    if request.method == 'POST':
        form_obj = model_form(data=request.POST)
        if form_obj.is_valid():
            form_obj.save()
            return redirect(reverse('djadmin:table_detail', kwargs={'app_name': app_name, 'model_name': model_name}))
    return render(request, 'djadmin/table_edit.html', locals())

# 数据删除
@login_required
def table_delete(request, app_name, model_name, obj_id):
    admin_class = site.enable_admins[app_name][model_name]
    obj = admin_class.model.objects.get(id=obj_id)
    if request.method == 'POST':
        if request.POST.get('delete_confirm') == 'yes':
            admin_class.model.objects.filter(id=obj_id).delete()
            return redirect(reverse('djadmin:table_detail', args=(app_name, model_name)))
    return render(request, 'djadmin/table_delete.html', locals())

djadmin/templates/djadmin/base.html
<!DOCTYPE html>
{% load static %}
{% load djadmin_tags %}
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}Feiu CRM后台管理系统{% endblock %}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap-3.3.7/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'bootstrap-3.3.7/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'bootstrap-3.3.7/css/dashboard.css' %}" rel="stylesheet">
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <script src="{% static 'bootstrap-3.3.7/js/ie-emulation-modes-warning.js' %}"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block css %}{% endblock %}
</head>

<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">FeiuCRM系统管理</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">功能</a></li>
                {% if request.user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ request.user }}<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">用户信息</a></li>
                            <li role="separator" class="divider"></li>
                            <li class="dropdown-header">当前用户：{{ request.user }}</li>
                            <li><a href="{% url 'djadmin:user_logout' %}">退出登录</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'djadmin:user_login' %}">点击登录</a></li>
                {% endif %}
            </ul>
<form class="navbar-form navbar-right">
    <input name="_kw" type="text" class="form-control" placeholder="Search..." value="{{ keyword }}">
</form>
        </div>
    </div>
</nav>

<div class="container-fluid">
    {% block body %}
        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                <ul class="nav nav-sidebar">
                   {% url 'djadmin:index' as djadmin_index %}
                    <li {% if request.path == djadmin_index %} class="active" {% endif %}><a href="{{ djadmin_index }}">后台首页</a></li>
                    {# request.user.userprofile.role.select_related #}
                    {% for role in request.user.userprofile.role.all %}
                        {% for menu in role.menus.all %}
                            {% if menu.url_type == 0 %}
                                <li {% if request.path == menu.url %} class="active" {% endif %}><a href="{{ menu.url }}">{{ menu.name }}</a></li>
                            {% else %}
                                {% url menu.url as menu_dynamic_url %}
                                <li {% if request.path == menu_dynamic_url %} class="active" {% endif %}><a href="{{ menu_url }}">{{ menu.name }}</a></li>
                            {% endif %}
                        {% endfor %}
                    {% endfor %}
                </ul>
            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    {% endblock body %}
</div>

<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'bootstrap-3.3.7/js/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap-3.3.7/js/bootstrap.min.js' %}"></script>
<!-- Just to make our placeholder images work. Don't actually copy the next line! -->
<script src="{% static 'bootstrap-3.3.7/js/holder.min.js' %}"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static 'bootstrap-3.3.7/js/ie10-viewport-bug-workaround.js' %}"></script>
{% block js %}{% endblock %}
</body>
</html>

djadmin/templates/djadmin/index.html
{% extends 'djadmin/base.html' %}

{% block title %}
    首页 - Feiu CRM后台管理
{% endblock %}

{% block content %}
     <h1 class="page-header">所有应用</h1>
    {% for app_name, app_models in site.enable_admins.items %}

        <table class="table table-striped">
            <thead>
            <tr>
                <th>{{ app_name }}</th>
            </tr>
            </thead>
            <tbody>
            {% for model_name in app_models %}
                <tr>
                <td><a href="{% url 'djadmin:table_detail' app_name=app_name model_name=model_name %}">{{ model_name }}</a></td>
                    <td><a href="{% url 'djadmin:table_add' app_name=app_name model_name=model_name %}">增加</a></td>
{#                    <td><a href="{% url 'djadmin:table_change' app_name=app_name model_name=model_name obj_id=1 %}">修改</a></td>#}
                 <td><a href="#">修改</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endfor %}
{% endblock %}

djadmin/templates/djadmin/login.html
{# djadmin/templates/djadmin/login.html #}
{% extends 'djadmin/base.html' %}
{% load static %}

{% block title %}
    登录 - 后台管理
{% endblock %}

{% block css %}
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
{% endblock %}

{% block body %}
    <div class="container">
        <form class="form-signin" method="post">
            <h2 class="form-signin-heading">请登录</h2>
            <label for="inputName" class="sr-only">用户名</label>
            <input type="text" id="inputName" name="username" class="form-control" placeholder="用户名" required="" autofocus="">
            <label for="inputPassword" class="sr-only">密码</label>
            <input type="password" id="inputPassword" name="password" class="form-control" placeholder="密码" required="">
            <p style="color: coral">{{ login_msg }}</p>
            <div class="checkbox">
                <label>
                    <input type="checkbox" value="remember-me"> 记住我
                </label>
            </div>
            {% csrf_token %}
            <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
        </form>

    </div> <!-- /container -->
{% endblock %}

djadmin/templates/djadmin/table_delete.html
{% extends 'djadmin/base.html' %}

{% load djadmin_tags %}

{% block title %}
    数据表删除 - 后台管理
{% endblock %}

{% block content %}
    <h2 class="page-header">{{ model_name }}</h2>
    <h3 class="page-header alert alert-danger">你确定要删除吗？</h3>

    <div>
        删除<a href="{% url 'djadmin:table_change' app_name model_name obj.id %}">【{{ obj }}】</a>
    </div>

    {% display_all_related_objs obj as all_related_obj_eles %}
    {{ all_related_obj_eles|safe }}  {# 需要加上|safe，否则会直接显示源代码 #}

    <form method="post">
        {% csrf_token %}
        <input class="hidden" value="yes" name="delete_confirm">
        <input type="submit" class="btn btn-danger" value="确认删除">
        <a class="btn btn-info" href="{% url 'djadmin:table_change' app_name model_name obj.id %}">返回编辑</a>
    </form>
{% endblock %}

djadmin/templates/djadmin/table_delete_objs.html
{% extends 'djadmin/base.html' %}

{% load djadmin_tags %}

{% block title %}
    数据表删除 - 后台管理
{% endblock %}

{% block content %}
    <h2 class="page-header">{{ model_name }}</h2>
    <h3 class="page-header alert alert-danger">你确定要删除吗？</h3>

    {% for obj in objs %}
        {% display_all_related_objs obj as all_related_obj_eles %}
        {{ all_related_obj_eles|safe }}  {# 需要加上|safe，否则会直接显示源代码 #}
    {% endfor %}

    <form method="post">
        {% csrf_token %}
        <input class="hidden" value="yes" name="delete_confirm">
        <input class="hidden" value="{{ action }}" name="action">
        <input class="hidden" value="{{ selected_ids }}" name="selected_ids">
        <input type="submit" class="btn btn-danger" value="确认删除">
    </form>
{% endblock %}

djadmin/templates/djadmin/table_detail.html
{% extends 'djadmin/base.html' %}

{% load djadmin_tags %}

{% block title %}
    数据表详情 - 后台管理
{% endblock %}

{% block content %}
    <h1 class="page-header">应用 - {{ app_name }}</h1>
    {{ queryset }}
{% if admin_class.list_filter %}
    <p>
        <form class="navbar-form navbar-left">
            {% for filter_field in admin_class.list_filter %}
                {% build_option_filter filter_field admin_class %}
            {% endfor %}
            <button type="submit" class="btn btn-primary">过滤</button>
        </form>
    </p>
{% endif %}
    <form method="post" onsubmit="ActionCheck(this)">
    <div class="row">
        <div class="col-md-3">
            <select class="form-control" name="action">
                <option value="">-------</option>
                {% for action in admin_class.actions %}
                    <option value="{{ action }}">{{ action }}</option>
                {% endfor %}
            </select>
        </div>
        {% csrf_token %}
        <div class="col-md-2">
            <input type="submit" value="执行" class="btn btn-primary">
        </div>
    </div>
</form>
    <table class="table table-striped">
        <thead>
        <tr>
        <th><input type="checkbox" onclick="SelectALLObjs(this)"></th>
        {% if admin_class.list_display %}
            {% for display_field in admin_class.list_display %}
                <th>
                    <a href="?_order={% get_sorted_data display_field current_order_field forloop.counter0 %}{% render_filter_args admin_class %}">
                        {{ display_field }} {% get_sorted_arrow display_field current_order_field forloop.counter0 %}
                    </a>
                </th>
            {% endfor %}
        {% else %}
            {% build_table_head_name admin_class %}
        {% endif %}
        <th>操作</th>
            <!--
            {% build_table_head_name admin_class %}
            -->
        </tr>
        </thead>
        <tbody>
            {% for obj in queryset %}
                <tr>
                    <td><input row-select="true" type="checkbox" value="{{ obj.id }}"></td>
                    {% build_table_body obj admin_class %}
                    <td><a href="{% url 'djadmin:table_delete' app_name model_name obj.id %}">删除</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div>
    {% include 'include/pagination.html' with page=queryset current_order_value=current_order_value %}
</div>
    <script>
    function SelectALLObjs(ele) {
        if ($(ele).prop('checked')){
            $('input[row-select]').prop('checked',true)
        }else{
             $('input[row-select]').prop('checked',false)
        }
    }
    function ActionCheck(ele) {
            let selected_action = $("select[name='action']").val();  // 获取选择的功能
            let selected_objs = $("input[row-select]").filter(":checked");  // 获取下方所有勾选
            console.log(selected_action);
            console.log(selected_objs);
            if (!selected_action){
                alert("没有选择的执行项！");
                return false
            }
            //alert(selected_objs.length);
            if (selected_objs.length == 0 ){
                alert("没有选择数据项！");
                return false
            } else {
                // 生成一个form标签，放在form里
                let selected_ids = [];
                $.each(selected_objs, function () {
                    console.log($(this));
                    selected_ids.push($(this).val())
                });
                console.log(selected_ids);
                let input_ele = "<input type='hidden' name='selected_ids' value=" + JSON.stringify(selected_ids) + ">";
                $(ele).append(input_ele);
            }
        }

</script>
{% endblock %}

djadmin/templates/djadmin/table_edit.html
{% extends 'djadmin/base.html' %}

{% load djadmin_tags %}

{% block title %}
    数据表编辑 - 后台管理
{% endblock %}

{% block content %}
    <h1 class="page-header">{{ app_name }} - {{ model_name }} - 编辑 &nbsp;&nbsp; {{ obj }} </h1>
    <!--<div>{{ form_obj }}</div>-->
    <form class="form-horizontal" method="post" onsubmit="VerificationBeforeFormSubmit();">
        {{ form_obj.errors }}

        {% for field in form_obj %}
            <div class="form-group">
                <label class="col-sm-2 control-label">{{ field.label }}</label>
                <div class="col-sm-10">
                    {% if field.name in admin_class.filter_horizontal %}
                        <!--字段名在多选的字段中，使用多选框-->
                        <div class="col-md-5">
                            <input type="search" class="form-control" oninput="FuzzySearch(this)" placeholder="模糊搜索">
                            <select multiple class="form-control" id="id_{{ field.name }}_from">
                                {% get_available_m2m_data field.name form_obj admin_class as vailable_m2m_data %}
                                {% for obj in vailable_m2m_data %}
                                    <option value="{{ obj.id }}" ondblclick="MoveSelectedOption(this,'id_{{ field.name }}_to')">{{ obj }}</option>
                                {% endfor %}
                            </select>
                        <p><a onclick="MoveAllElements('id_{{ field.name }}_from', 'id_{{ field.name }}_to')">全选></a></p>
                        </div>
                        <div class="col-md-5">
                            <select myflag="selected_m2m" multiple class="form-control" id="id_{{ field.name }}_to" name="{{ field.name }}">
                                {% get_selected_m2m_data field.name form_obj admin_class as selected_m2m_data %}
                                {% for obj in selected_m2m_data %}
                                    <option value="{{ obj.id }}" ondblclick="MoveSelectedOption(this,'id_{{ field.name }}_from')">{{ obj }}</option>
                                {% endfor %}
                            </select>
                         <p><a onclick="MoveAllElements('id_{{ field.name }}_to', 'id_{{ field.name }}_from')"><删除全部</a></p>
                        </div>
                    {% else %}
                        {{ field }}
                    {% endif %}
                    <span style="color: red">{{ field.errors.0 }}</span>
                </div>
            </div>
        {% endfor %}
        {% csrf_token %}

        {% if not admin_class.form_add %}
            {# 当修改数据时，才显示下方只读字段，当增加数据时，下方则不会显示 #}
            {% for field in admin_class.readonly_fields %}
                <label class="col-sm-2 control-label">{{ field }}</label>
                <div class="col-sm-10">
                    <p>{% get_obj_field_val form_obj field %}</p>
                </div>
            {% endfor %}
        {% endif %}

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-4">
                <button type="submit" class="btn btn-primary">提交</button>
            </div>
            {% url 'djadmin:table_add' app_name model_name as table_add %}
                {% if request.path != table_add %}
                <div class="col-sm-offset-2 col-sm-4">
                    <a class="btn btn-danger" href="{% url 'djadmin:table_delete' app_name model_name obj_id %}">删除</a>
                </div>
            {% endif %}
        </div>
    </form>

    <script>
        function MoveSelectedOption(ele, target_id) {
            let new_target_id = $(ele).parent().attr('id');
            let option = "<option value='" + $(ele).val() +"'ondblclick=MoveSelectedOption(this,'"+ new_target_id +"') >" + $(ele).text() +"</option>";
            //将双击的元素添加到另一方
            $("#"+ target_id).append(option);
            //移除本方的元素
            $(ele).remove();
        }

        function VerificationBeforeFormSubmit() {
            //提交表单时选中所有的select
            $("select[myflag] option").prop('selected', true);
        }

        function MoveAllElements(from_id, to_id) {
        console.log($("#" + from_id).children())
        $("#" + from_id).children().each(function () {
            MoveSelectedOption(this, to_id);
        })
    }

       function FuzzySearch(ele) {
        //过滤多选框中的数据
        console.log($(ele).val());
        let search_text = $(ele).val().toUpperCase();
        $(ele).next().children().each(function () {
            if ($(this).text().toUpperCase().search(search_text) !== -1) {
                $(this).show();
            } else {
                $(this).hide();
            }
        })
    }
    </script>
{% endblock %}